version: '3'

services:
  iris-web:
    build: .
    ports:
      - "16649:16649"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_CFG_DB_HOST=iris-mysql
      - IRIS_CFG_DB_PASSWORD=1234
      - ONCALL_API=http://oncall:8080
      - ONCALL_KEY=magic
      - ONCALL_APP=oncall
      
      
    depends_on:
      - iris-mysql
    volumes:
      - ./configs/config.dev.yaml:/home/iris/config/config.yaml

  iris-mysql:
    image: mysql:9.4
    command: mysqld
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
